SMLSHARP = \
../SMLSharp/src/compiler/smlsharp \
 -B../SMLSharp/src/nativeruntime \
 -I../SMLSharp/src/lib2 \

.SUFFIXES: .sml .o

FILES = \
basis/test/Array001.sml \
basis/test/Array101.sml \
basis/test/ArraySlice001.sml \
basis/test/ArraySlice101.sml \
basis/test/Bool001.sml \
basis/test/Byte001.sml \
basis/test/Char001.sml \
basis/test/CharArray001.sml \
basis/test/CharArray101.sml \
basis/test/CharArraySlice001.sml \
basis/test/CharArraySlice101.sml \
basis/test/CharVector001.sml \
basis/test/CharVector101.sml \
basis/test/CharVectorSlice001.sml \
basis/test/CharVectorSlice101.sml \
basis/test/Date001.sml \
basis/test/General001.sml \
basis/test/IEEEReal001.sml \
basis/test/ImmutableSequence001.sml \
basis/test/ImmutableSequenceSlice001.sml \
basis/test/Int001.sml \
basis/test/IntInf001.sml \
basis/test/IntInf101.sml \
basis/test/LargeInt001.sml \
basis/test/LargeWord001.sml \
basis/test/List001.sml \
basis/test/ListPair001.sml \
basis/test/main_MLton.sml \
basis/test/Math001.sml \
basis/test/MutableSequence001.sml \
basis/test/MutableSequenceSlice001.sml \
basis/test/Option001.sml \
basis/test/Position001.sml \
basis/test/Real001.sml \
basis/test/Sequence101.sml \
basis/test/SequenceSlice101.sml \
basis/test/SignedInteger001.sml \
basis/test/String001.sml \
basis/test/StringCvt001.sml \
basis/test/Substring001.sml \
basis/test/TestMain.sml \
basis/test/TestRequiredModules.sml \
basis/test/TestOptionalModules_SMLSharp.sml \
basis/test/Time001.sml \
basis/test/UnsignedInteger001.sml \
basis/test/Vector001.sml \
basis/test/Vector101.sml \
basis/test/VectorSlice001.sml \
basis/test/VectorSlice101.sml \
basis/test/Word001.sml \
basis/test/Word8001.sml \
basis/test/Word8Array001.sml \
basis/test/Word8Array101.sml \
basis/test/Word8ArraySlice001.sml \
basis/test/Word8ArraySlice101.sml \
basis/test/Word8Vector001.sml \
basis/test/Word8Vector101.sml \
basis/test/Word8VectorSlice001.sml \
basis/test/Word8VectorSlice101.sml \
src/main/Assert.sml \
src/main/SMLUnit.sml \
src/main/Test.sml \
src/main/TextUITestRunner.sml

all: dotest

dotest: $(FILES:.sml=.o)
	$(SMLSHARP) -o $@ basis/test/main_MLton.smi

clean:
	-rm -f $(FILES:.sml=.o)

.sml.o:
	$(SMLSHARP) -c $< -o $@

depend:
	$(SMLSHARP) -M $(FILES)

basis/test/Array001.o: basis/test/Array001.sml \
  src/main/ASSERT.sig src/main/Assert.smi src/main/TEST.sig src/main/Test.smi \
  src/main/TESTRUNNER.sig src/main/TextUITestRunner.smi src/main/SMLUNIT.sig \
  src/main/SMLUnit.smi basis/test/SEQUENCE.sig basis/test/MUTABLE_SEQUENCE.sig \
  basis/test/MutableSequence001.smi basis/test/Array001.smi
basis/test/Array101.o: basis/test/Array101.sml \
  src/main/ASSERT.sig src/main/Assert.smi src/main/TEST.sig src/main/Test.smi \
  src/main/TESTRUNNER.sig src/main/TextUITestRunner.smi src/main/SMLUNIT.sig \
  src/main/SMLUnit.smi basis/test/SEQUENCE.sig basis/test/Sequence101.smi \
  basis/test/Array101.smi
basis/test/ArraySlice001.o: basis/test/ArraySlice001.sml \
  src/main/ASSERT.sig src/main/Assert.smi src/main/TEST.sig src/main/Test.smi \
  src/main/TESTRUNNER.sig src/main/TextUITestRunner.smi src/main/SMLUNIT.sig \
  src/main/SMLUnit.smi basis/test/SEQUENCE_SLICE.sig \
  basis/test/MUTABLE_SEQUENCE_SLICE.sig basis/test/MutableSequenceSlice001.smi \
  basis/test/ArraySlice001.smi
basis/test/ArraySlice101.o: basis/test/ArraySlice101.sml \
  src/main/ASSERT.sig src/main/Assert.smi src/main/TEST.sig src/main/Test.smi \
  src/main/TESTRUNNER.sig src/main/TextUITestRunner.smi src/main/SMLUNIT.sig \
  src/main/SMLUnit.smi basis/test/SEQUENCE.sig basis/test/SEQUENCE_SLICE.sig \
  basis/test/SequenceSlice101.smi basis/test/ArraySlice101.smi
basis/test/Bool001.o: basis/test/Bool001.sml \
  src/main/ASSERT.sig src/main/Assert.smi src/main/TEST.sig src/main/Test.smi \
  src/main/TESTRUNNER.sig src/main/TextUITestRunner.smi src/main/SMLUNIT.sig \
  src/main/SMLUnit.smi basis/test/Bool001.smi
basis/test/Byte001.o: basis/test/Byte001.sml \
  src/main/ASSERT.sig src/main/Assert.smi src/main/TEST.sig src/main/Test.smi \
  src/main/TESTRUNNER.sig src/main/TextUITestRunner.smi src/main/SMLUNIT.sig \
  src/main/SMLUnit.smi basis/test/Byte001.smi
basis/test/Char001.o: basis/test/Char001.sml \
  src/main/ASSERT.sig src/main/Assert.smi src/main/TEST.sig src/main/Test.smi \
  src/main/TESTRUNNER.sig src/main/TextUITestRunner.smi src/main/SMLUNIT.sig \
  src/main/SMLUnit.smi basis/test/Char001.smi
basis/test/CharArray001.o: basis/test/CharArray001.sml \
  src/main/ASSERT.sig src/main/Assert.smi src/main/TEST.sig src/main/Test.smi \
  src/main/TESTRUNNER.sig src/main/TextUITestRunner.smi src/main/SMLUNIT.sig \
  src/main/SMLUnit.smi basis/test/SEQUENCE.sig basis/test/MUTABLE_SEQUENCE.sig \
  basis/test/MutableSequence001.smi basis/test/CharArray001.smi
basis/test/CharArray101.o: basis/test/CharArray101.sml \
  src/main/ASSERT.sig src/main/Assert.smi src/main/TEST.sig src/main/Test.smi \
  src/main/TESTRUNNER.sig src/main/TextUITestRunner.smi src/main/SMLUNIT.sig \
  src/main/SMLUnit.smi basis/test/SEQUENCE.sig basis/test/Sequence101.smi \
  basis/test/CharArray101.smi
basis/test/CharArraySlice001.o: basis/test/CharArraySlice001.sml \
  src/main/ASSERT.sig src/main/Assert.smi src/main/TEST.sig src/main/Test.smi \
  src/main/TESTRUNNER.sig src/main/TextUITestRunner.smi src/main/SMLUNIT.sig \
  src/main/SMLUnit.smi basis/test/SEQUENCE_SLICE.sig \
  basis/test/MUTABLE_SEQUENCE_SLICE.sig basis/test/MutableSequenceSlice001.smi \
  basis/test/CharArraySlice001.smi
basis/test/CharArraySlice101.o: basis/test/CharArraySlice101.sml \
  src/main/ASSERT.sig src/main/Assert.smi src/main/TEST.sig src/main/Test.smi \
  src/main/TESTRUNNER.sig src/main/TextUITestRunner.smi src/main/SMLUNIT.sig \
  src/main/SMLUnit.smi basis/test/SEQUENCE.sig basis/test/SEQUENCE_SLICE.sig \
  basis/test/SequenceSlice101.smi basis/test/CharArraySlice101.smi
basis/test/CharVector001.o: basis/test/CharVector001.sml \
  src/main/ASSERT.sig src/main/Assert.smi src/main/TEST.sig src/main/Test.smi \
  src/main/TESTRUNNER.sig src/main/TextUITestRunner.smi src/main/SMLUNIT.sig \
  src/main/SMLUnit.smi basis/test/SEQUENCE.sig \
  basis/test/IMMUTABLE_SEQUENCE.sig basis/test/ImmutableSequence001.smi \
  basis/test/CharVector001.smi
basis/test/CharVector101.o: basis/test/CharVector101.sml \
  src/main/ASSERT.sig src/main/Assert.smi src/main/TEST.sig src/main/Test.smi \
  src/main/TESTRUNNER.sig src/main/TextUITestRunner.smi src/main/SMLUNIT.sig \
  src/main/SMLUnit.smi basis/test/SEQUENCE.sig basis/test/Sequence101.smi \
  basis/test/CharVector101.smi
basis/test/CharVectorSlice001.o: basis/test/CharVectorSlice001.sml \
  src/main/ASSERT.sig src/main/Assert.smi src/main/TEST.sig src/main/Test.smi \
  src/main/TESTRUNNER.sig src/main/TextUITestRunner.smi src/main/SMLUNIT.sig \
  src/main/SMLUnit.smi basis/test/SEQUENCE_SLICE.sig \
  basis/test/IMMUTABLE_SEQUENCE_SLICE.sig \
  basis/test/ImmutableSequenceSlice001.smi basis/test/CharVectorSlice001.smi
basis/test/CharVectorSlice101.o: basis/test/CharVectorSlice101.sml \
  src/main/ASSERT.sig src/main/Assert.smi src/main/TEST.sig src/main/Test.smi \
  src/main/TESTRUNNER.sig src/main/TextUITestRunner.smi src/main/SMLUNIT.sig \
  src/main/SMLUnit.smi basis/test/SEQUENCE.sig basis/test/SEQUENCE_SLICE.sig \
  basis/test/SequenceSlice101.smi basis/test/CharVectorSlice101.smi
basis/test/Date001.o: basis/test/Date001.sml \
  src/main/ASSERT.sig src/main/Assert.smi src/main/TEST.sig src/main/Test.smi \
  src/main/TESTRUNNER.sig src/main/TextUITestRunner.smi src/main/SMLUNIT.sig \
  src/main/SMLUnit.smi basis/test/Date001.smi
basis/test/General001.o: basis/test/General001.sml \
  src/main/ASSERT.sig src/main/Assert.smi src/main/TEST.sig src/main/Test.smi \
  src/main/TESTRUNNER.sig src/main/TextUITestRunner.smi src/main/SMLUNIT.sig \
  src/main/SMLUnit.smi basis/test/General001.smi
basis/test/IEEEReal001.o: basis/test/IEEEReal001.sml \
  src/main/ASSERT.sig src/main/Assert.smi src/main/TEST.sig src/main/Test.smi \
  src/main/TESTRUNNER.sig src/main/TextUITestRunner.smi src/main/SMLUNIT.sig \
  src/main/SMLUnit.smi basis/test/IEEEReal001.smi
basis/test/ImmutableSequence001.o: basis/test/ImmutableSequence001.sml \
  src/main/ASSERT.sig src/main/Assert.smi src/main/TEST.sig src/main/Test.smi \
  src/main/TESTRUNNER.sig src/main/TextUITestRunner.smi src/main/SMLUNIT.sig \
  src/main/SMLUnit.smi basis/test/SEQUENCE.sig \
  basis/test/IMMUTABLE_SEQUENCE.sig basis/test/ImmutableSequence001.smi
basis/test/ImmutableSequenceSlice001.o: \
  basis/test/ImmutableSequenceSlice001.sml \
  src/main/ASSERT.sig src/main/Assert.smi src/main/TEST.sig src/main/Test.smi \
  src/main/TESTRUNNER.sig src/main/TextUITestRunner.smi src/main/SMLUNIT.sig \
  src/main/SMLUnit.smi basis/test/SEQUENCE_SLICE.sig \
  basis/test/IMMUTABLE_SEQUENCE_SLICE.sig \
  basis/test/ImmutableSequenceSlice001.smi
basis/test/Int001.o: basis/test/Int001.sml \
  src/main/ASSERT.sig src/main/Assert.smi src/main/TEST.sig src/main/Test.smi \
  src/main/TESTRUNNER.sig src/main/TextUITestRunner.smi src/main/SMLUNIT.sig \
  src/main/SMLUnit.smi basis/test/SignedInteger001.smi basis/test/Int001.smi
basis/test/IntInf001.o: basis/test/IntInf001.sml \
  src/main/ASSERT.sig src/main/Assert.smi src/main/TEST.sig src/main/Test.smi \
  src/main/TESTRUNNER.sig src/main/TextUITestRunner.smi src/main/SMLUNIT.sig \
  src/main/SMLUnit.smi basis/test/SignedInteger001.smi \
  basis/test/IntInf001.smi
basis/test/IntInf101.o: basis/test/IntInf101.sml \
  src/main/ASSERT.sig src/main/Assert.smi src/main/TEST.sig src/main/Test.smi \
  src/main/TESTRUNNER.sig src/main/TextUITestRunner.smi src/main/SMLUNIT.sig \
  src/main/SMLUnit.smi basis/test/IntInf101.smi
basis/test/LargeInt001.o: basis/test/LargeInt001.sml \
  src/main/ASSERT.sig src/main/Assert.smi src/main/TEST.sig src/main/Test.smi \
  src/main/TESTRUNNER.sig src/main/TextUITestRunner.smi src/main/SMLUNIT.sig \
  src/main/SMLUnit.smi basis/test/SignedInteger001.smi \
  basis/test/LargeInt001.smi
basis/test/LargeWord001.o: basis/test/LargeWord001.sml \
  src/main/ASSERT.sig src/main/Assert.smi src/main/TEST.sig src/main/Test.smi \
  src/main/TESTRUNNER.sig src/main/TextUITestRunner.smi src/main/SMLUNIT.sig \
  src/main/SMLUnit.smi basis/test/UnsignedInteger001.smi \
  basis/test/LargeWord001.smi
basis/test/List001.o: basis/test/List001.sml \
  src/main/ASSERT.sig src/main/Assert.smi src/main/TEST.sig src/main/Test.smi \
  src/main/TESTRUNNER.sig src/main/TextUITestRunner.smi src/main/SMLUNIT.sig \
  src/main/SMLUnit.smi basis/test/List001.smi
basis/test/ListPair001.o: basis/test/ListPair001.sml \
  src/main/ASSERT.sig src/main/Assert.smi src/main/TEST.sig src/main/Test.smi \
  src/main/TESTRUNNER.sig src/main/TextUITestRunner.smi src/main/SMLUNIT.sig \
  src/main/SMLUnit.smi basis/test/ListPair001.smi
basis/test/main_MLton.o: basis/test/main_MLton.sml \
  src/main/ASSERT.sig src/main/Assert.smi src/main/TEST.sig src/main/Test.smi \
  src/main/TESTRUNNER.sig src/main/TextUITestRunner.smi src/main/SMLUNIT.sig \
  src/main/SMLUnit.smi basis/test/SEQUENCE.sig basis/test/MUTABLE_SEQUENCE.sig \
  basis/test/MutableSequence001.smi basis/test/Array001.smi \
  basis/test/Sequence101.smi basis/test/Array101.smi \
  basis/test/SEQUENCE_SLICE.sig basis/test/MUTABLE_SEQUENCE_SLICE.sig \
  basis/test/MutableSequenceSlice001.smi basis/test/ArraySlice001.smi \
  basis/test/SequenceSlice101.smi basis/test/ArraySlice101.smi \
  basis/test/Bool001.smi basis/test/Byte001.smi basis/test/Char001.smi \
  basis/test/CharArray001.smi basis/test/CharArray101.smi \
  basis/test/CharArraySlice001.smi basis/test/CharArraySlice101.smi \
  basis/test/IMMUTABLE_SEQUENCE.sig basis/test/ImmutableSequence001.smi \
  basis/test/CharVector001.smi basis/test/CharVector101.smi \
  basis/test/IMMUTABLE_SEQUENCE_SLICE.sig \
  basis/test/ImmutableSequenceSlice001.smi basis/test/CharVectorSlice001.smi \
  basis/test/CharVectorSlice101.smi basis/test/Date001.smi \
  basis/test/General001.smi basis/test/IEEEReal001.smi \
  basis/test/SignedInteger001.smi basis/test/Int001.smi \
  basis/test/LargeInt001.smi basis/test/UnsignedInteger001.smi \
  basis/test/LargeWord001.smi basis/test/List001.smi \
  basis/test/ListPair001.smi basis/test/Math001.smi basis/test/Option001.smi \
  basis/test/Position001.smi basis/test/Real001.smi \
  basis/test/StringCvt001.smi basis/test/String001.smi \
  basis/test/Substring001.smi basis/test/Time001.smi basis/test/Vector001.smi \
  basis/test/Vector101.smi basis/test/VectorSlice001.smi \
  basis/test/VectorSlice101.smi basis/test/Word001.smi basis/test/Word8001.smi \
  basis/test/Word8Array001.smi basis/test/Word8Array101.smi \
  basis/test/Word8ArraySlice001.smi basis/test/Word8ArraySlice101.smi \
  basis/test/Word8Vector001.smi basis/test/Word8Vector101.smi \
  basis/test/Word8VectorSlice101.smi basis/test/Word8VectorSlice001.smi \
  basis/test/TestRequiredModules.smi basis/test/IntInf001.smi \
  basis/test/IntInf101.smi basis/test/TestOptionalModules_SMLSharp.smi \
  basis/test/TestMain.smi basis/test/main_MLton.smi
basis/test/Math001.o: basis/test/Math001.sml \
  src/main/ASSERT.sig src/main/Assert.smi src/main/TEST.sig src/main/Test.smi \
  src/main/TESTRUNNER.sig src/main/TextUITestRunner.smi src/main/SMLUNIT.sig \
  src/main/SMLUnit.smi basis/test/Math001.smi
basis/test/MutableSequence001.o: basis/test/MutableSequence001.sml \
  src/main/ASSERT.sig src/main/Assert.smi src/main/TEST.sig src/main/Test.smi \
  src/main/TESTRUNNER.sig src/main/TextUITestRunner.smi src/main/SMLUNIT.sig \
  src/main/SMLUnit.smi basis/test/SEQUENCE.sig basis/test/MUTABLE_SEQUENCE.sig \
  basis/test/MutableSequence001.smi
basis/test/MutableSequenceSlice001.o: basis/test/MutableSequenceSlice001.sml \
  src/main/ASSERT.sig src/main/Assert.smi src/main/TEST.sig src/main/Test.smi \
  src/main/TESTRUNNER.sig src/main/TextUITestRunner.smi src/main/SMLUNIT.sig \
  src/main/SMLUnit.smi basis/test/SEQUENCE_SLICE.sig \
  basis/test/MUTABLE_SEQUENCE_SLICE.sig basis/test/MutableSequenceSlice001.smi
basis/test/Option001.o: basis/test/Option001.sml \
  src/main/ASSERT.sig src/main/Assert.smi src/main/TEST.sig src/main/Test.smi \
  src/main/TESTRUNNER.sig src/main/TextUITestRunner.smi src/main/SMLUNIT.sig \
  src/main/SMLUnit.smi basis/test/Option001.smi
basis/test/Position001.o: basis/test/Position001.sml \
  src/main/ASSERT.sig src/main/Assert.smi src/main/TEST.sig src/main/Test.smi \
  src/main/TESTRUNNER.sig src/main/TextUITestRunner.smi src/main/SMLUNIT.sig \
  src/main/SMLUnit.smi basis/test/SignedInteger001.smi \
  basis/test/Position001.smi
basis/test/Real001.o: basis/test/Real001.sml \
  src/main/ASSERT.sig src/main/Assert.smi src/main/TEST.sig src/main/Test.smi \
  src/main/TESTRUNNER.sig src/main/TextUITestRunner.smi src/main/SMLUNIT.sig \
  src/main/SMLUnit.smi basis/test/Real001.smi
basis/test/Sequence101.o: basis/test/Sequence101.sml \
  src/main/ASSERT.sig src/main/Assert.smi src/main/TEST.sig src/main/Test.smi \
  src/main/TESTRUNNER.sig src/main/TextUITestRunner.smi src/main/SMLUNIT.sig \
  src/main/SMLUnit.smi basis/test/SEQUENCE.sig basis/test/Sequence101.smi
basis/test/SequenceSlice101.o: basis/test/SequenceSlice101.sml \
  src/main/ASSERT.sig src/main/Assert.smi src/main/TEST.sig src/main/Test.smi \
  src/main/TESTRUNNER.sig src/main/TextUITestRunner.smi src/main/SMLUNIT.sig \
  src/main/SMLUnit.smi basis/test/SEQUENCE.sig basis/test/SEQUENCE_SLICE.sig \
  basis/test/SequenceSlice101.smi
basis/test/SignedInteger001.o: basis/test/SignedInteger001.sml \
  src/main/ASSERT.sig src/main/Assert.smi src/main/TEST.sig src/main/Test.smi \
  src/main/TESTRUNNER.sig src/main/TextUITestRunner.smi src/main/SMLUNIT.sig \
  src/main/SMLUnit.smi basis/test/SignedInteger001.smi
basis/test/String001.o: basis/test/String001.sml \
  src/main/ASSERT.sig src/main/Assert.smi src/main/TEST.sig src/main/Test.smi \
  src/main/TESTRUNNER.sig src/main/TextUITestRunner.smi src/main/SMLUNIT.sig \
  src/main/SMLUnit.smi basis/test/String001.smi
basis/test/StringCvt001.o: basis/test/StringCvt001.sml \
  src/main/ASSERT.sig src/main/Assert.smi src/main/TEST.sig src/main/Test.smi \
  src/main/TESTRUNNER.sig src/main/TextUITestRunner.smi src/main/SMLUNIT.sig \
  src/main/SMLUnit.smi basis/test/StringCvt001.smi
basis/test/Substring001.o: basis/test/Substring001.sml \
  src/main/ASSERT.sig src/main/Assert.smi src/main/TEST.sig src/main/Test.smi \
  src/main/TESTRUNNER.sig src/main/TextUITestRunner.smi src/main/SMLUNIT.sig \
  src/main/SMLUnit.smi basis/test/Substring001.smi
basis/test/TestMain.o: basis/test/TestMain.sml \
  src/main/ASSERT.sig src/main/Assert.smi src/main/TEST.sig src/main/Test.smi \
  src/main/TESTRUNNER.sig src/main/TextUITestRunner.smi src/main/SMLUNIT.sig \
  src/main/SMLUnit.smi basis/test/SEQUENCE.sig basis/test/MUTABLE_SEQUENCE.sig \
  basis/test/MutableSequence001.smi basis/test/Array001.smi \
  basis/test/Sequence101.smi basis/test/Array101.smi \
  basis/test/SEQUENCE_SLICE.sig basis/test/MUTABLE_SEQUENCE_SLICE.sig \
  basis/test/MutableSequenceSlice001.smi basis/test/ArraySlice001.smi \
  basis/test/SequenceSlice101.smi basis/test/ArraySlice101.smi \
  basis/test/Bool001.smi basis/test/Byte001.smi basis/test/Char001.smi \
  basis/test/CharArray001.smi basis/test/CharArray101.smi \
  basis/test/CharArraySlice001.smi basis/test/CharArraySlice101.smi \
  basis/test/IMMUTABLE_SEQUENCE.sig basis/test/ImmutableSequence001.smi \
  basis/test/CharVector001.smi basis/test/CharVector101.smi \
  basis/test/IMMUTABLE_SEQUENCE_SLICE.sig \
  basis/test/ImmutableSequenceSlice001.smi basis/test/CharVectorSlice001.smi \
  basis/test/CharVectorSlice101.smi basis/test/Date001.smi \
  basis/test/General001.smi basis/test/IEEEReal001.smi \
  basis/test/SignedInteger001.smi basis/test/Int001.smi \
  basis/test/LargeInt001.smi basis/test/UnsignedInteger001.smi \
  basis/test/LargeWord001.smi basis/test/List001.smi \
  basis/test/ListPair001.smi basis/test/Math001.smi basis/test/Option001.smi \
  basis/test/Position001.smi basis/test/Real001.smi \
  basis/test/StringCvt001.smi basis/test/String001.smi \
  basis/test/Substring001.smi basis/test/Time001.smi basis/test/Vector001.smi \
  basis/test/Vector101.smi basis/test/VectorSlice001.smi \
  basis/test/VectorSlice101.smi basis/test/Word001.smi basis/test/Word8001.smi \
  basis/test/Word8Array001.smi basis/test/Word8Array101.smi \
  basis/test/Word8ArraySlice001.smi basis/test/Word8ArraySlice101.smi \
  basis/test/Word8Vector001.smi basis/test/Word8Vector101.smi \
  basis/test/Word8VectorSlice101.smi basis/test/Word8VectorSlice001.smi \
  basis/test/TestRequiredModules.smi basis/test/IntInf001.smi \
  basis/test/IntInf101.smi basis/test/TestOptionalModules_SMLSharp.smi \
  basis/test/TestMain.smi
basis/test/TestRequiredModules.o: basis/test/TestRequiredModules.sml \
  src/main/ASSERT.sig src/main/Assert.smi src/main/TEST.sig src/main/Test.smi \
  src/main/TESTRUNNER.sig src/main/TextUITestRunner.smi src/main/SMLUNIT.sig \
  src/main/SMLUnit.smi basis/test/SEQUENCE.sig basis/test/MUTABLE_SEQUENCE.sig \
  basis/test/MutableSequence001.smi basis/test/Array001.smi \
  basis/test/Sequence101.smi basis/test/Array101.smi \
  basis/test/SEQUENCE_SLICE.sig basis/test/MUTABLE_SEQUENCE_SLICE.sig \
  basis/test/MutableSequenceSlice001.smi basis/test/ArraySlice001.smi \
  basis/test/SequenceSlice101.smi basis/test/ArraySlice101.smi \
  basis/test/Bool001.smi basis/test/Byte001.smi basis/test/Char001.smi \
  basis/test/CharArray001.smi basis/test/CharArray101.smi \
  basis/test/CharArraySlice001.smi basis/test/CharArraySlice101.smi \
  basis/test/IMMUTABLE_SEQUENCE.sig basis/test/ImmutableSequence001.smi \
  basis/test/CharVector001.smi basis/test/CharVector101.smi \
  basis/test/IMMUTABLE_SEQUENCE_SLICE.sig \
  basis/test/ImmutableSequenceSlice001.smi basis/test/CharVectorSlice001.smi \
  basis/test/CharVectorSlice101.smi basis/test/Date001.smi \
  basis/test/General001.smi basis/test/IEEEReal001.smi \
  basis/test/SignedInteger001.smi basis/test/Int001.smi \
  basis/test/LargeInt001.smi basis/test/UnsignedInteger001.smi \
  basis/test/LargeWord001.smi basis/test/List001.smi \
  basis/test/ListPair001.smi basis/test/Math001.smi basis/test/Option001.smi \
  basis/test/Position001.smi basis/test/Real001.smi \
  basis/test/StringCvt001.smi basis/test/String001.smi \
  basis/test/Substring001.smi basis/test/Time001.smi basis/test/Vector001.smi \
  basis/test/Vector101.smi basis/test/VectorSlice001.smi \
  basis/test/VectorSlice101.smi basis/test/Word001.smi basis/test/Word8001.smi \
  basis/test/Word8Array001.smi basis/test/Word8Array101.smi \
  basis/test/Word8ArraySlice001.smi basis/test/Word8ArraySlice101.smi \
  basis/test/Word8Vector001.smi basis/test/Word8Vector101.smi \
  basis/test/Word8VectorSlice101.smi basis/test/Word8VectorSlice001.smi \
  basis/test/TestRequiredModules.smi
basis/test/TestOptionalModules_SMLSharp.o: \
  basis/test/TestOptionalModules_SMLSharp.sml \
  src/main/ASSERT.sig src/main/Assert.smi src/main/TEST.sig src/main/Test.smi \
  src/main/TESTRUNNER.sig src/main/TextUITestRunner.smi src/main/SMLUNIT.sig \
  src/main/SMLUnit.smi basis/test/SignedInteger001.smi \
  basis/test/IntInf001.smi basis/test/IntInf101.smi \
  basis/test/TestOptionalModules_SMLSharp.smi
basis/test/Time001.o: basis/test/Time001.sml \
  src/main/ASSERT.sig src/main/Assert.smi src/main/TEST.sig src/main/Test.smi \
  src/main/TESTRUNNER.sig src/main/TextUITestRunner.smi src/main/SMLUNIT.sig \
  src/main/SMLUnit.smi basis/test/Time001.smi
basis/test/UnsignedInteger001.o: basis/test/UnsignedInteger001.sml \
  src/main/ASSERT.sig src/main/Assert.smi src/main/TEST.sig src/main/Test.smi \
  src/main/TESTRUNNER.sig src/main/TextUITestRunner.smi src/main/SMLUNIT.sig \
  src/main/SMLUnit.smi basis/test/UnsignedInteger001.smi
basis/test/Vector001.o: basis/test/Vector001.sml \
  src/main/ASSERT.sig src/main/Assert.smi src/main/TEST.sig src/main/Test.smi \
  src/main/TESTRUNNER.sig src/main/TextUITestRunner.smi src/main/SMLUNIT.sig \
  src/main/SMLUnit.smi basis/test/SEQUENCE.sig \
  basis/test/IMMUTABLE_SEQUENCE.sig basis/test/ImmutableSequence001.smi \
  basis/test/Vector001.smi
basis/test/Vector101.o: basis/test/Vector101.sml \
  src/main/ASSERT.sig src/main/Assert.smi src/main/TEST.sig src/main/Test.smi \
  src/main/TESTRUNNER.sig src/main/TextUITestRunner.smi src/main/SMLUNIT.sig \
  src/main/SMLUnit.smi basis/test/SEQUENCE.sig basis/test/Sequence101.smi \
  basis/test/Vector101.smi
basis/test/VectorSlice001.o: basis/test/VectorSlice001.sml \
  src/main/ASSERT.sig src/main/Assert.smi src/main/TEST.sig src/main/Test.smi \
  src/main/TESTRUNNER.sig src/main/TextUITestRunner.smi src/main/SMLUNIT.sig \
  src/main/SMLUnit.smi basis/test/SEQUENCE_SLICE.sig \
  basis/test/IMMUTABLE_SEQUENCE_SLICE.sig \
  basis/test/ImmutableSequenceSlice001.smi basis/test/VectorSlice001.smi
basis/test/VectorSlice101.o: basis/test/VectorSlice101.sml \
  src/main/ASSERT.sig src/main/Assert.smi src/main/TEST.sig src/main/Test.smi \
  src/main/TESTRUNNER.sig src/main/TextUITestRunner.smi src/main/SMLUNIT.sig \
  src/main/SMLUnit.smi basis/test/SEQUENCE.sig basis/test/SEQUENCE_SLICE.sig \
  basis/test/SequenceSlice101.smi basis/test/VectorSlice101.smi
basis/test/Word001.o: basis/test/Word001.sml \
  src/main/ASSERT.sig src/main/Assert.smi src/main/TEST.sig src/main/Test.smi \
  src/main/TESTRUNNER.sig src/main/TextUITestRunner.smi src/main/SMLUNIT.sig \
  src/main/SMLUnit.smi basis/test/UnsignedInteger001.smi \
  basis/test/Word001.smi
basis/test/Word8001.o: basis/test/Word8001.sml \
  src/main/ASSERT.sig src/main/Assert.smi src/main/TEST.sig src/main/Test.smi \
  src/main/TESTRUNNER.sig src/main/TextUITestRunner.smi src/main/SMLUNIT.sig \
  src/main/SMLUnit.smi basis/test/UnsignedInteger001.smi \
  basis/test/Word8001.smi
basis/test/Word8Array001.o: basis/test/Word8Array001.sml \
  src/main/ASSERT.sig src/main/Assert.smi src/main/TEST.sig src/main/Test.smi \
  src/main/TESTRUNNER.sig src/main/TextUITestRunner.smi src/main/SMLUNIT.sig \
  src/main/SMLUnit.smi basis/test/SEQUENCE.sig basis/test/MUTABLE_SEQUENCE.sig \
  basis/test/MutableSequence001.smi basis/test/Word8Array001.smi
basis/test/Word8Array101.o: basis/test/Word8Array101.sml \
  src/main/ASSERT.sig src/main/Assert.smi src/main/TEST.sig src/main/Test.smi \
  src/main/TESTRUNNER.sig src/main/TextUITestRunner.smi src/main/SMLUNIT.sig \
  src/main/SMLUnit.smi basis/test/SEQUENCE.sig basis/test/Sequence101.smi \
  basis/test/Word8Array101.smi
basis/test/Word8ArraySlice001.o: basis/test/Word8ArraySlice001.sml \
  src/main/ASSERT.sig src/main/Assert.smi src/main/TEST.sig src/main/Test.smi \
  src/main/TESTRUNNER.sig src/main/TextUITestRunner.smi src/main/SMLUNIT.sig \
  src/main/SMLUnit.smi basis/test/SEQUENCE_SLICE.sig \
  basis/test/MUTABLE_SEQUENCE_SLICE.sig basis/test/MutableSequenceSlice001.smi \
  basis/test/Word8ArraySlice001.smi
basis/test/Word8ArraySlice101.o: basis/test/Word8ArraySlice101.sml \
  src/main/ASSERT.sig src/main/Assert.smi src/main/TEST.sig src/main/Test.smi \
  src/main/TESTRUNNER.sig src/main/TextUITestRunner.smi src/main/SMLUNIT.sig \
  src/main/SMLUnit.smi basis/test/SEQUENCE.sig basis/test/SEQUENCE_SLICE.sig \
  basis/test/SequenceSlice101.smi basis/test/Word8ArraySlice101.smi
basis/test/Word8Vector001.o: basis/test/Word8Vector001.sml \
  src/main/ASSERT.sig src/main/Assert.smi src/main/TEST.sig src/main/Test.smi \
  src/main/TESTRUNNER.sig src/main/TextUITestRunner.smi src/main/SMLUNIT.sig \
  src/main/SMLUnit.smi basis/test/SEQUENCE.sig \
  basis/test/IMMUTABLE_SEQUENCE.sig basis/test/ImmutableSequence001.smi \
  basis/test/Word8Vector001.smi
basis/test/Word8Vector101.o: basis/test/Word8Vector101.sml \
  src/main/ASSERT.sig src/main/Assert.smi src/main/TEST.sig src/main/Test.smi \
  src/main/TESTRUNNER.sig src/main/TextUITestRunner.smi src/main/SMLUNIT.sig \
  src/main/SMLUnit.smi basis/test/SEQUENCE.sig basis/test/SEQUENCE_SLICE.sig \
  basis/test/SequenceSlice101.smi basis/test/Sequence101.smi \
  basis/test/Word8Vector101.smi
basis/test/Word8VectorSlice001.o: basis/test/Word8VectorSlice001.sml \
  src/main/ASSERT.sig src/main/Assert.smi src/main/TEST.sig src/main/Test.smi \
  src/main/TESTRUNNER.sig src/main/TextUITestRunner.smi src/main/SMLUNIT.sig \
  src/main/SMLUnit.smi basis/test/SEQUENCE_SLICE.sig \
  basis/test/IMMUTABLE_SEQUENCE_SLICE.sig \
  basis/test/ImmutableSequenceSlice001.smi basis/test/Word8VectorSlice001.smi
basis/test/Word8VectorSlice101.o: basis/test/Word8VectorSlice101.sml \
  src/main/ASSERT.sig src/main/Assert.smi src/main/TEST.sig src/main/Test.smi \
  src/main/TESTRUNNER.sig src/main/TextUITestRunner.smi src/main/SMLUNIT.sig \
  src/main/SMLUnit.smi basis/test/SEQUENCE.sig basis/test/SEQUENCE_SLICE.sig \
  basis/test/SequenceSlice101.smi basis/test/Word8VectorSlice101.smi
src/main/Assert.o: src/main/Assert.sml \
  src/main/ASSERT.sig src/main/Assert.smi
src/main/SMLUnit.o: src/main/SMLUnit.sml \
  src/main/ASSERT.sig src/main/Assert.smi src/main/TEST.sig src/main/Test.smi \
  src/main/TESTRUNNER.sig src/main/TextUITestRunner.smi src/main/SMLUNIT.sig \
  src/main/SMLUnit.smi
src/main/Test.o: src/main/Test.sml  \
  src/main/TEST.sig src/main/Test.smi
src/main/TextUITestRunner.o: src/main/TextUITestRunner.sml \
  src/main/ASSERT.sig src/main/Assert.smi src/main/TEST.sig src/main/Test.smi \
  src/main/TESTRUNNER.sig src/main/TextUITestRunner.smi
