#!/bin/sh

set -e
cd $(dirname "$0")

get_version () {
  desc=$(git describe --match='v[0-9]*' --tags --long)
  args=$(echo "$desc" | sed -E 's/^v(.*)-([0-9]+)-g([a-f0-9]+)$/\1 \2 \3/')
  set -- $args
  case "$2" in
    "")
      return 1
      ;;
    0)
      version="$1"
      date=$(git for-each-ref --format='%(creatordate:iso)' "refs/tags/v$1")
      ;;
    *)
      case "$1" in
        *-*)
          version="$1.$2.g$3"
          ;;
        *)
          version=$(echo "$1" | awk -v FS=. -v OFS=. '{$3+=1;print}')
          version="$version-$2.g$3"
          ;;
      esac
      date=$(git log -1 --format='%ci')
      ;;
  esac
  release="$version ($(echo "$date" | sed 's/+0900/JST/'))"
}

case "$1" in
  version)
    get_version
    echo "$version"
    ;;

  release)
    if get_version; then
      echo "$release"
    elif release=$(git log -1 --format='-g%h (%ci)'); then
      echo "$release" | sed 's/+0900/JST/'
    else
      echo '(unknown)'
    fi
    ;;

  package)
    get_version
    TAR=tar
    $TAR --version | grep 'GNU tar' > /dev/null 2>&1 || TAR=gtar
    tmp=$(mktemp -d)
    trap 'rm -rf "$tmp"' EXIT
    trap 'exit 127' INT QUIT STOP
    root="$tmp/smlsharp-$version"
    mkdir "$root"
    git archive -o "$tmp/archive.tar" HEAD
    $TAR -C "$root" -xf "$tmp/archive.tar"
    echo "$release" > "$root/RELEASE"
    rm -r "$root/.github"
    $TAR -cf "smlsharp-$version.tar.gz" -C "$tmp" --sort=name \
         --format=ustar --use-compress-program='gzip -c -n -9' \
         --owner=root:0 --group=root:0 --mtime="$date" \
         "smlsharp-$version"
    hash=$(sha256sum < "smlsharp-$version.tar.gz")
    echo "version=$version"
    echo "date=$date"
    echo "filename=smlsharp-$version.tar.gz"
    echo "hash=${hash%% *}"
    ;;

  history)
    get_version
    tmp=$(mktemp -d)
    trap 'rm -rf "$tmp"' EXIT
    trap 'exit 127' INT QUIT STOP
    dst="smlsharp-$version.history"
    git tag -l 'v[0-9]*' --merged=HEAD --sort=-creatordate \
            --format='%(objecttype) %(refname) %(creatordate:iso)' \
            >> "$tmp/tags"
    sed -i~ -E 's|^[a-z]+ refs/tags/v||' "$tmp/tags"
    echo "$version $date" > "$tmp/history"
    cat "$tmp/tags" >> "$tmp/history"
    uniq "$tmp/history" > "smlsharp-$version.history"
    ;;

  *)
    exit 1
    ;;
esac
