(**
 * definition of constants used by ML parser.
 * @author OHORI Atsushi
 * @author YAMATODANI Kiyoshi
 * @version $Id: ParserConstants_SMLNJ.sml,v 1.1 2006/11/13 13:15:47 kiyoshiy Exp $
 *)
structure ParserConstants =
struct

  (* NOTE: Because of a bug (?) in source code generated by ML-lex of SML/NJ,
   * beginPos of the first line is 2, not 0.
   * If SML/NJ ML-lex is changed, this value should be updated also.
   *)
  val INITIAL_POS_OF_LEXER = 2

end;
