(**
 * @author YAMATODANI Kiyoshi
 * @copyright 2010, Tohoku University.
 *)
structure Constants =
struct

  (* NOTE: Because of a bug (?) in source code generated by ML-lex of SML/NJ,
   * beginPos of the first line is 2, not 0.
   * If SML/NJ ML-lex is changed, this value should be updated also.
   *)
  val INITIAL_POS_OF_LEXER = 2

end